# Generated by Django 3.2.4 on 2021-07-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeViewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='variation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='recipeViewer.recipe'),
        ),
    ]
