version: '3'

services:
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    env_file: 
      - .env
      - .postgresql.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD", "nc","-z","localhost","5432"]
        interval: 30s
        timeout: 10s
        retries: 5
  web:
      container_name: django
      build: ./
      command: python3 manage.py runserver 0.0.0.0:8000
      env_file:
        - .env
      ports:
        - 8000:8000
      depends_on: 
        db:
      restart: on-failure

volumes:
  postgres-data:
